/**
 * Google Maps place categories the Apify actor accepts in `categoryFilterWords`
 * — a CLOSED, all-lowercase enum. A value outside it (including the SAME word in
 * Title case) 400s the run start: "must be equal to one of the allowed values".
 *
 * GENERATED FILE — do not hand-edit. Refresh with:
 *   node backend/scripts/refresh-place-categories.mjs
 *
 * Source: apify.com/compass/crawler-google-places build 0.14.720 (2026-07-27).
 */
export const GOOGLE_PLACE_CATEGORIES = Object.freeze([
  '3d printing service', 'abarth dealer', 'abbey',
  'aboriginal and torres strait islander organisation', 'aboriginal art gallery',
  'abortion clinic', 'abrasives supplier', 'abundant life church', 'academic department',
  'acaraje restaurant', 'accountant', 'accounting', 'accounting firm', 'accounting school',
  'acoustical consultant', 'acrobatic diving pool', 'acrylic store', 'acupuncture clinic',
  'acupuncture school', 'acupuncturist', 'acura dealer', 'addiction treatment center',
  'administrative attorney', 'adoption agency', 'adult day care center', 'adult dvd store',
  'adult education school', 'adult entertainment club', 'adult entertainment store',
  'adult foster care service', 'adventure sports center', 'advertising agency',
  'advertising photographer', 'advertising service', 'aerated drinks supplier',
  'aerial photographer', 'aerial sports center', 'aero dance class', 'aerobics instructor',
  'aeroclub', 'aeromodel shop', 'aeronautical engineer', 'aerospace company',
  'afghan restaurant', 'african goods store', 'african restaurant', 'after school program',
  'agenzia entrate', 'aggregate supplier', 'agistment service', 'agricultural association',
  'agricultural cooperative', 'agricultural engineer', 'agricultural high school',
  'agricultural machinery manufacturer', 'agricultural organization',
  'agricultural product wholesaler', 'agricultural production', 'agricultural service',
  'agriculture', 'agrochemicals supplier', 'aikido club', 'aikido school',
  'air compressor repair service', 'air compressor supplier', 'air conditioning contractor',
  'air conditioning repair service', 'air conditioning store',
  'air conditioning system supplier', 'air duct cleaning service', 'air filter supplier',
  'air force base', 'air taxi', 'airbrushing service', 'airbrushing supply store',
  'aircraft dealer', 'aircraft maintenance company', 'aircraft manufacturer',
  'aircraft rental service', 'aircraft supply store', 'airline', 'airline ticket agency',
  'airport', 'airport shuttle service', 'airstrip', 'alcohol manufacturer',
  'alcohol retail monopoly', 'alcoholic beverage wholesaler', 'alcoholism treatment program',
  'alfa romeo dealer', 'allergist', 'alliance church', 'alsace restaurant',
  'alternative fuel station', 'alternative medicine clinic',
  'alternative medicine practitioner', 'alternator supplier', 'aluminium supplier',
  'aluminum frames supplier', 'aluminum supplier', 'aluminum welder', 'aluminum window',
  'ambulance service', 'american grocery store', 'american restaurant', 'amish furniture store',
  'ammunition supplier', 'amphitheater', 'amphitheatre', 'amusement center',
  'amusement machine supplier', 'amusement park', 'amusement park ride',
  'amusement ride supplier', 'anago restaurant', 'andalusian restaurant', 'andhra restaurant',
  'anesthesiologist', 'anganwadi center', 'angler fish restaurant', 'anglican church',
  'animal control service', 'animal feed store', 'animal hospital',
  'animal protection organization', 'animal rescue service', 'animal shelter',
  'animal watering hole', 'animation studio', 'anime club', 'antenna service',
  'antique furniture restoration service', 'antique furniture store', 'antique store',
  'apartment building', 'apartment complex', 'apartment rental agency', 'apostolic church',
  'apparel company', 'appliance parts supplier', 'appliance rental service',
  'appliance repair service', 'appliance store', 'appliances customer service', 'appraiser',
  'apprenticeship center', 'aquaculture farm', 'aquarium', 'aquarium shop', 'aquatic centre',
  'arab restaurant', 'arboretum', 'arborist service', 'archaeological museum', 'archery club',
  'archery range', 'archery store', 'architect', 'architects association',
  'architectural and engineering model maker', 'architectural designer',
  'architectural salvage store', 'architecture firm', 'architecture school', 'archive', 'arena',
  'argentinian restaurant', 'armed forces association', 'armenian church',
  'armenian restaurant', 'army & navy surplus shop', 'army facility', 'army museum',
  'aromatherapy class', 'aromatherapy service', 'aromatherapy supply store', 'art cafe',
  'art center', 'art dealer', 'art gallery', 'art museum', 'art restoration service',
  'art school', 'art studio', 'art supply store', 'artificial plant supplier', 'artist',
  'artistic handicrafts', 'arts organization', 'asbestos testing service', 'ashram',
  'asian fusion restaurant', 'asian grocery store', 'asian household goods store',
  'asian restaurant', 'asphalt contractor', 'asphalt mixing plant', 'assamese restaurant',
  'assemblies of god church', 'assistante maternelle', 'assisted living facility',
  'association / organization', 'aston martin dealer', 'astrologer', 'asturian restaurant',
  'athletic club', 'athletic field', 'athletic park', 'athletic track', 'atm', 'attorney',
  'attorney referral service', 'atv dealer', 'atv rental service', 'atv repair shop',
  'auction house', 'audi dealer', 'audio visual consultant',
  'audio visual equipment repair service', 'audio visual equipment supplier', 'audiologist',
  'audiovisual equipment rental service', 'auditor', 'auditorium', 'australian goods store',
  'australian restaurant', 'austrian restaurant', 'auto accessories wholesaler',
  'auto air conditioning service', 'auto auction', 'auto body parts supplier', 'auto body shop',
  'auto bodywork mechanic', 'auto broker', 'auto care products store', 'auto chemistry shop',
  'auto dent removal service', 'auto electrical service', 'auto glass repair service',
  'auto glass shop', 'auto insurance agency', 'auto machine shop', 'auto market',
  'auto painting', 'auto parts manufacturer', 'auto parts market', 'auto parts store',
  'auto radiator repair service', 'auto repair shop', 'auto restoration service',
  'auto rickshaw stand', 'auto spring shop', 'auto sunroof shop', 'auto tag agency',
  'auto tune up service', 'auto upholsterer', 'auto window tinting service', 'auto wrecker',
  'automation company', 'automobile storage facility', 'aviation consultant',
  'aviation training institute', 'awadhi restaurant', 'awning supplier',
  'ayam penyet restaurant', 'ayurvedic clinic', 'azerbaijani restaurant', 'açaí shop',
  'baby clothing store', 'baby store', 'baby swimming school', 'baden restaurant',
  'badminton club', 'badminton complex', 'badminton court', 'bag shop', 'bagel shop',
  'bail bonds service', 'bait shop', 'bakery', 'bakery equipment', 'baking supply store',
  'bakso restaurant', 'balinese restaurant', 'ballet school', 'ballet theater',
  'balloon artist', 'balloon ride tour agency', 'balloon store', 'ballroom dance instructor',
  'band', 'bangladeshi restaurant', 'bangle shop', 'bank', 'banking and finance',
  'bankruptcy attorney', 'bankruptcy service', 'banner store', 'banquet hall', 'baptist church',
  'bar', 'bar pmu', 'bar restaurant furniture store', 'bar stool supplier', 'bar tabac',
  'barbecue area', 'barbecue restaurant', 'barber school', 'barber shop', 'barber supply store',
  'bariatric surgeon', 'bark supplier', 'barrel supplier', 'barrister', 'bartending school',
  'baseball club', 'baseball field', 'baseball goods store', 'basilica', 'basket supplier',
  'basketball club', 'basketball court', 'basketball court contractor', 'basque restaurant',
  'batak restaurant', 'bathroom remodeler', 'bathroom renovator', 'bathroom supply store',
  'batik clothing store', 'battery manufacturer', 'battery store', 'battery wholesaler',
  'batting cage center', 'bavarian restaurant', 'bazar', 'beach', 'beach cleaning service',
  'beach clothing store', 'beach club', 'beach entertainment shop', 'beach pavillion',
  'beach volleyball club', 'beach volleyball court', 'bead store', 'bead wholesaler',
  'bearing supplier', 'beautician', 'beauty parlour', 'beauty product supplier',
  'beauty products vending machine', 'beauty products wholesaler', 'beauty salon',
  'beauty school', 'beauty supply store', 'bed & breakfast', 'bed shop', 'bedding store',
  'bedroom furniture store', 'bee relocation service', 'beer distributor', 'beer garden',
  'beer hall', 'beer store', 'belgian restaurant', 'belt shop', 'bengali restaurant',
  'bentley dealer', 'berry restaurant', 'betawi restaurant', 'betting agency',
  'beverage distributor', 'beverage supplier', 'bicycle club', 'bicycle rack',
  'bicycle rental service', 'bicycle repair shop', 'bicycle shop', 'bicycle store',
  'bicycle wholesaler', 'bike sharing station', 'bike wash', 'bikram yoga studio',
  'bilingual school', 'billiards supply store', 'bingo hall', 'biochemistry lab',
  'biofeedback therapist', 'biotechnology company', 'bird control service', 'bird shop',
  'bird watching area', 'birth center', 'birth certificate service', 'birth control center',
  'biryani restaurant', 'bistro', 'blacksmith', 'blast cleaning service', 'blinds shop',
  'blood bank', 'blood donation center', 'blood testing service', 'blueprint service',
  'blues club', 'bmw dealer', 'bmw motorcycle dealer', 'bmx club', 'bmx park',
  'board game club', 'board of education', 'boarding house', 'boarding school',
  'boat accessories supplier', 'boat builders', 'boat cleaning service', 'boat club',
  'boat cover supplier', 'boat dealer', 'boat detailing service', 'boat ramp',
  'boat rental service', 'boat repair shop', 'boat storage facility', 'boat tour agency',
  'boat trailer dealer', 'boating instructor', 'bocce ball court', 'bodega',
  'body piercing shop', 'body shaping class', 'boiler manufacturer', 'boiler supplier',
  'bonesetting house', 'bonsai plant supplier', 'book publisher', 'book store', 'bookbinder',
  'bookkeeping service', 'books wholesaler', 'boot camp', 'boot repair shop', 'boot store',
  'border crossing station', 'border guard', 'botanica', 'botanical garden',
  'bottle & can redemption center', 'bottled water supplier', 'bouncy castle hire', 'boutique',
  'bowling alley', 'bowling club', 'bowling supply shop', 'box lunch supplier', 'boxing club',
  'boxing gym', 'boxing ring', 'boys\' high school', 'boys\' hostel', 'bpo company',
  'bpo placement agency', 'brake shop', 'branding agency', 'brasserie', 'brazilian pastelaria',
  'brazilian restaurant', 'breakfast restaurant', 'brewery', 'brewing supply store', 'brewpub',
  'brick manufacturer', 'bricklayer', 'bridal shop', 'bridge', 'bridge club',
  'british restaurant', 'brunch restaurant', 'bubble tea store', 'buddhist supplies store',
  'buddhist temple', 'buffet restaurant', 'bugatti dealer', 'buick dealer', 'builder',
  'building', 'building consultant', 'building designer', 'building equipment hire service',
  'building firm', 'building inspector', 'building materials market',
  'building materials store', 'building materials supplier', 'building restoration service',
  'building society', 'bulgarian restaurant', 'bullring', 'bungee jumping center',
  'burglar alarm store', 'burmese restaurant', 'burrito restaurant', 'bus charter',
  'bus company', 'bus depot', 'bus station', 'bus stop', 'bus ticket agency', 'bus tour agency',
  'business administration service', 'business attorney', 'business banking service',
  'business broker', 'business center', 'business development service',
  'business management consultant', 'business networking company', 'business park',
  'business school', 'business to business service', 'butane gas supplier', 'butcher shop',
  'butcher shop deli', 'butchers', 'butsudan store', 'cabaret club', 'cabin rental agency',
  'cabinet maker', 'cabinet store', 'cable company', 'cadillac dealer', 'cafe', 'cafeteria',
  'cajun restaurant', 'cake decorating equipment shop', 'cake shop', 'californian restaurant',
  'call center', 'call shop', 'calligraphy lesson', 'calvary chapel church',
  'cambodian restaurant', 'camera repair shop', 'camera store', 'camper shell supplier',
  'campground', 'camping cabin', 'camping farm', 'camping store', 'canadian restaurant',
  'cancer treatment center', 'candle store', 'candy store', 'cane furniture store',
  'cannabis club', 'cannabis store', 'cannery', 'canoe & kayak store',
  'canoe & kayak tour agency', 'canoe and kayak club', 'canoeing area', 'cantabrian restaurant',
  'cantonese restaurant', 'cape verdean restaurant', 'capoeira school', 'capsule hotel',
  'car accessories store', 'car alarm supplier', 'car battery store', 'car dealer',
  'car detailing service', 'car factory', 'car finance and loan company',
  'car inspection station', 'car leasing service', 'car manufacturer', 'car rental agency',
  'car repair and maintenance service', 'car security system installer', 'car sharing location',
  'car stereo store', 'car wash', 'carabinieri police', 'cardiologist',
  'cardiovascular and thoracic surgeon', 'care services', 'career guidance service',
  'caribbean restaurant', 'carnival club', 'carpenter', 'carpet cleaning service',
  'carpet installer', 'carpet manufacturer', 'carpet store', 'carpet wholesaler',
  'carport and pergola builder', 'carriage ride service', 'cars', 'carvery',
  'cash and carry wholesaler', 'cashpoint', 'casino', 'casket service', 'castilian restaurant',
  'castle', 'cat boarding service', 'cat breeder', 'cat cafe', 'cat trainer',
  'catalonian restaurant', 'caterer', 'catering', 'catering food and drink supplier',
  'cathedral', 'catholic cathedral', 'catholic church', 'catholic school', 'cattery',
  'cattle farm', 'cattle market', 'caucasian restaurant', 'cbse school', 'cd store',
  'ceiling supplier', 'cell phone accessory store', 'cell phone charging station',
  'cell phone store', 'cement manufacturer', 'cement supplier', 'cemetery', 'cendol restaurant',
  'central american restaurant', 'central bank', 'central european restaurant',
  'central heating service', 'central javanese restaurant', 'ceramic manufacturer',
  'ceramics wholesaler', 'certification agency', 'certified public accountant', 'chalet',
  'chamber of agriculture', 'chamber of commerce', 'chamber of handicrafts',
  'champon noodle restaurant', 'chapel', 'charcuterie', 'charity', 'charter school',
  'chartered accountant', 'chauffeur service', 'check cashing service', 'cheese manufacturer',
  'cheese shop', 'cheesesteak restaurant', 'chemical exporter', 'chemical industry',
  'chemical manufacturer', 'chemical plant', 'chemical wholesaler', 'chemist', 'chemistry lab',
  'chesapeake restaurant', 'chess and card club', 'chess club', 'chess instructor',
  'chevrolet dealer', 'chicken restaurant', 'chicken shop', 'chicken wings restaurant',
  'child care agency', 'child health care centre', 'child psychiatrist', 'child psychologist',
  'childbirth class', 'childminder', 'children hall', 'children policlinic',
  'children\'s amusement center', 'children\'s cafe', 'children\'s camp',
  'children\'s clothing store', 'children\'s club', 'children\'s furniture store',
  'children\'s health service', 'children\'s hospital', 'children\'s party buffet',
  'children\'s party service', 'children\'s store', 'childrens store', 'chilean restaurant',
  'chimney services', 'chimney sweep', 'chinaware store', 'chinese bakery',
  'chinese language instructor', 'chinese language school', 'chinese medicine clinic',
  'chinese medicine store', 'chinese noodle restaurant', 'chinese restaurant',
  'chinese supermarket', 'chinese takeaway', 'chinese tea house', 'chiropractor',
  'chocolate artisan', 'chocolate cafe', 'chocolate factory', 'chocolate shop', 'choir',
  'chop bar', 'chophouse restaurant', 'christian book store', 'christian church',
  'christian college', 'christmas market', 'christmas store', 'christmas tree farm',
  'chrysler dealer', 'church', 'church of christ',
  'church of jesus christ of latter-day saints', 'church of the nazarene',
  'church supply store', 'churreria', 'cider bar', 'cider mill', 'cig kofte restaurant',
  'cigar shop', 'cinema equipment supplier', 'circus', 'citizen information bureau',
  'citroen dealer', 'city courthouse', 'city department of transportation',
  'city district office', 'city employment department', 'city government office', 'city hall',
  'city park', 'city tax office', 'civic center', 'civil engineer', 'civil engineering company',
  'civil examinations academy', 'civil law attorney', 'civil police',
  'classified ads newspaper publisher', 'cleaners', 'cleaning products supplier',
  'cleaning service', 'clergyman', 'clinic', 'clock and watch maker', 'clock repair service',
  'closed circuit television', 'clothes and fabric manufacturer',
  'clothes and fabric wholesaler', 'clothes market', 'clothing alteration service',
  'clothing manufacturer', 'clothing shop', 'clothing store', 'clothing supplier',
  'clothing wholesale market place', 'clothing wholesaler', 'club', 'co-ed school',
  'coach and minibus hire', 'coaching center', 'coaching service', 'coal exporter',
  'coal supplier', 'coalfield', 'coast guard station', 'cocktail bar',
  'coffee machine supplier', 'coffee roasters', 'coffee shop', 'coffee stand', 'coffee store',
  'coffee vending machine', 'coffee wholesaler', 'coffin supplier', 'coin dealer',
  'coin operated laundry equipment supplier', 'coin operated locker', 'cold cut store',
  'cold noodle restaurant', 'cold storage facility', 'collectibles store', 'college',
  'college of agriculture', 'colombian restaurant', 'combined primary and secondary school',
  'comedy club', 'comic book store', 'comic cafe', 'commercial agent',
  'commercial photographer', 'commercial printer', 'commercial real estate agency',
  'commercial real estate inspector', 'commercial refrigerator supplier',
  'commissioner for oaths', 'community center', 'community college', 'community garden',
  'community health center', 'community health centre', 'community school', 'company',
  'company registry', 'comprehensive secondary school', 'compressed natural gas station',
  'computer accessories store', 'computer club', 'computer consultant', 'computer desk store',
  'computer hardware manufacturer', 'computer networking service', 'computer repair service',
  'computer security service', 'computer service', 'computer shop', 'computer software store',
  'computer store', 'computer support and services', 'computer training school',
  'computer wholesaler', 'computers', 'concert hall', 'concrete contractor', 'concrete factory',
  'concrete metal framework supplier', 'concrete product supplier', 'condiments supplier',
  'condominium complex', 'condominium rental agency', 'confectionery store',
  'confectionery wholesaler', 'conference center', 'congregation', 'conservative club',
  'conservative synagogue', 'conservatory of music', 'consignment shop', 'construction',
  'construction company', 'construction equipment supplier', 'construction machine dealer',
  'construction machine rental service', 'construction material wholesaler', 'consultant',
  'consumer advice center', 'contact lenses supplier', 'container service',
  'container supplier', 'container terminal', 'containers supplier',
  'contemporary louisiana restaurant', 'continental restaurant', 'contractor',
  'convenience store', 'convention center', 'convention information bureau', 'conveyancer',
  'conveyor belt sushi restaurant', 'cookie shop', 'cooking class', 'cooking school',
  'cooling plant', 'cooperative bank', 'copier repair service', 'copper supplier',
  'coppersmith', 'copy shop', 'copying supply store', 'copywriting service', 'corporate campus',
  'corporate gift supplier', 'corporate office', 'cosmetic dentist',
  'cosmetic products manufacturer', 'cosmetic surgeon', 'cosmetics industry', 'cosmetics shop',
  'cosmetics store', 'cosmetics wholesaler', 'cosplay cafe', 'cost accounting service',
  'costa rican restaurant', 'costume jewelry shop', 'costume rental service', 'costume store',
  'cottage', 'cottage rental', 'cottage village', 'cotton exporter', 'cotton mill',
  'cotton supplier', 'council', 'counselor', 'countertop contractor', 'countertop store',
  'country club', 'country food restaurant', 'country house', 'country park',
  'county government office', 'courier service', 'court executive officer', 'court reporter',
  'courthouse', 'couscous restaurant', 'coworking space', 'crab house', 'craft store',
  'cramming school', 'crane dealer', 'crane rental agency', 'crane service',
  'craniosacral therapy', 'creative cuisine restaurant', 'credit counseling service',
  'credit reporting agency', 'credit union', 'cremation service', 'creole restaurant',
  'creperie', 'cricket club', 'cricket ground', 'cricket shop', 'crime victim service',
  'criminal justice attorney', 'croatian restaurant', 'crop grower', 'croquet club',
  'cruise agency', 'cruise terminal', 'crushed stone supplier', 'crypto atm',
  'cuban restaurant', 'culinary school', 'cultural association', 'cultural center',
  'cultural landmark', 'cupcake shop', 'cupra dealer', 'cured ham bar', 'cured ham store',
  'cured ham warehouse', 'curling club', 'curling hall', 'currency exchange service',
  'curtain store', 'curtain supplier and maker', 'custom confiscated goods store',
  'custom home builder', 'custom label printer', 'custom t-shirt store', 'custom tailor',
  'customs broker', 'customs consultant', 'customs office', 'customs warehouse',
  'cutlery store', 'cycle rickshaw stand', 'cycling park', 'czech restaurant', 'dacia dealer',
  'daihatsu dealer', 'dairy', 'dairy farm', 'dairy farm equipment supplier', 'dairy store',
  'dairy supplier', 'dan dan noodle restaurant', 'dance club', 'dance company', 'dance hall',
  'dance pavillion', 'dance restaurant', 'dance school', 'dance store', 'danish restaurant',
  'dart bar', 'dart supply store', 'data entry service', 'data recovery service',
  'database management company', 'dating service', 'day care center', 'day spa',
  'day-use onsen', 'deaf church', 'deaf service', 'dealer of fiat professional',
  'debris removal service', 'debt collecting', 'debt collection agency', 'decal supplier',
  'deck builder', 'deli', 'delicatessen', 'delivery chinese restaurant', 'delivery restaurant',
  'delivery service', 'demolition contractor', 'dental clinic', 'dental hygienist',
  'dental implants periodontist', 'dental implants provider', 'dental insurance agency',
  'dental laboratory', 'dental radiology', 'dental school', 'dental supply store', 'dentist',
  'denture care center', 'department of housing', 'department of motor vehicles',
  'department of public safety', 'department of social services',
  'department of transportation', 'department store', 'dermatologist', 'desalination plant',
  'design', 'design agency', 'design engineer', 'design institute', 'designer clothing store',
  'desktop publishing service', 'dessert restaurant', 'dessert shop', 'detention center',
  'dhaba', 'diabetes center', 'diabetes equipment supplier', 'diabetologist',
  'diagnostic center', 'dialysis center', 'diamond buyer', 'diamond dealer', 'diaper service',
  'diesel engine dealer', 'diesel engine repair service', 'diesel fuel supplier', 'dietitian',
  'digital printer', 'digital printing service', 'dim sum restaurant', 'diner',
  'dinner theater', 'direct mail advertising', 'dirt supplier', 'disability equipment supplier',
  'disability services and support organization', 'disc golf course',
  'disciples of christ church', 'disco club', 'discount store', 'discount supermarket',
  'display stand manufacturer', 'disposable tableware supplier', 'distance learning center',
  'distillery', 'distribution service', 'district attorney', 'district government office',
  'district justice', 'district office', 'dive club', 'dive shop', 'diving center',
  'divorce lawyer', 'divorce service', 'dj', 'dj service', 'dj supply store',
  'do-it-yourself shop', 'dock builder', 'doctor', 'dodge dealer', 'dog breeder', 'dog cafe',
  'dog day care center', 'dog park', 'dog trainer', 'dog walker', 'dogsled ride service',
  'dojo restaurant', 'doll restoration service', 'doll store', 'dollar store',
  'domestic abuse treatment center', 'domestic airport', 'dominican restaurant',
  'donations center', 'doner kebab restaurant', 'donut shop', 'door manufacturer', 'door shop',
  'door supplier', 'door warehouse', 'double glazing installer', 'doula',
  'drafting equipment supplier', 'drafting service', 'drainage service', 'drama school',
  'drawing lessons', 'dress and tuxedo rental service', 'dress shop', 'dress store',
  'dressmaker', 'dried flower shop', 'dried seafood store', 'drilling contractor',
  'drilling equipment supplier', 'drinking water fountain', 'driver\'s license office',
  'drivers license training school', 'driveshaft shop', 'driving school', 'driving test center',
  'drone service', 'drone shop', 'drug store', 'drug testing service', 'drum school',
  'drum store', 'dry cleaner', 'dry fruit store', 'dry ice supplier', 'dry wall contractor',
  'dry wall supply store', 'dryer vent cleaning service', 'ds automobiles dealer',
  'ducati dealer', 'dude ranch', 'dump truck dealer', 'dumpling restaurant',
  'dumpster rental service', 'durum restaurant', 'dutch restaurant', 'duty free store',
  'dvd store', 'dye store', 'dyeworks', 'dynamometer supplier', 'e commerce agency',
  'e-commerce service', 'ear piercing service', 'earth works company',
  'east african restaurant', 'east javanese restaurant', 'eastern european restaurant',
  'eastern orthodox church', 'eatery', 'eating disorder treatment center',
  'eclectic restaurant', 'ecological park', 'ecologists association', 'economic consultant',
  'economic development agency', 'ecuadorian restaurant', 'education', 'education center',
  'education centre', 'educational consultant', 'educational institution',
  'educational supply store', 'educational testing service', 'eftpos equipment supplier',
  'egg supplier', 'egyptian restaurant', 'elder law attorney', 'electric bicycle store',
  'electric generator shop', 'electric motor repair shop', 'electric motor scooter dealer',
  'electric motor store', 'electric motor vehicle dealer', 'electric motorcycle dealer',
  'electric utility company', 'electric vehicle charging station',
  'electric vehicle charging station contractor', 'electrical appliance wholesaler',
  'electrical engineer', 'electrical equipment supplier', 'electrical installation service',
  'electrical products wholesaler', 'electrical repair shop', 'electrical substation',
  'electrical supply store', 'electrician', 'electrolysis hair removal service',
  'electronic engineering service', 'electronic parts supplier', 'electronics',
  'electronics accessories wholesaler', 'electronics company', 'electronics engineer',
  'electronics hire shop', 'electronics manufacturer', 'electronics repair shop',
  'electronics retail and repair shop', 'electronics store', 'electronics vending machine',
  'electronics wholesaler', 'elementary school', 'elevator manufacturer', 'elevator service',
  'embassy', 'embossing service', 'embroidery service', 'embroidery shop',
  'emdr psychotherapist', 'emergency care physician', 'emergency care service',
  'emergency dental service', 'emergency locksmith service', 'emergency room',
  'emergency training', 'emergency training school', 'emergency veterinarian service',
  'employment agency', 'employment attorney', 'employment center', 'employment consultant',
  'endocrinologist', 'endodontist', 'endoscopist', 'energy equipment and solutions',
  'energy supplier', 'engine rebuilding service', 'engineer', 'engineering consultant',
  'engineering school', 'english language camp', 'english language school',
  'english restaurant', 'engraver', 'entertainer', 'entertainment', 'entertainment agency',
  'envelope supplier', 'environment office', 'environment renewable natural resources',
  'environmental consultant', 'environmental engineer', 'environmental health service',
  'environmental organization', 'environmental protection organization', 'episcopal church',
  'equestrian club', 'equestrian facility', 'equestrian store', 'equipment exporter',
  'equipment importer', 'equipment rental agency', 'equipment supplier', 'eritrean restaurant',
  'erotic massage', 'escape room center', 'escrow service', 'espresso bar', 'establishment',
  'estate agent', 'estate appraiser', 'estate liquidator', 'estate planning attorney',
  'ethiopian restaurant', 'ethnographic museum', 'european restaurant', 'evangelical church',
  'evening school', 'event management company', 'event planner', 'event planning service',
  'event technology service', 'event ticket seller', 'event venue', 'excavating contractor',
  'executive search firm', 'executive suite rental agency', 'executor',
  'exercise equipment store', 'exhibit', 'exhibition and trade centre', 'exhibition planner',
  'exporter', 'extended stay hotel', 'eye care center', 'eyebrow bar', 'eyelash salon',
  'fabric product manufacturer', 'fabric store', 'fabric wholesaler', 'fabrication engineer',
  'facial spa', 'factory equipment supplier', 'faculty of law', 'faculty of pharmacy',
  'faculty of science', 'fairground', 'falafel restaurant', 'family counselor',
  'family day care service', 'family law attorney', 'family planning center',
  'family planning counselor', 'family practice physician', 'family restaurant',
  'family service center', 'farm', 'farm bureau', 'farm equipment repair service',
  'farm equipment supplier', 'farm household tour', 'farm school', 'farm shop',
  'farmers\' market', 'farming and cattle raising', 'farmstay', 'farrier service',
  'fashion accessories shop', 'fashion accessories store', 'fashion design school',
  'fashion designer', 'fast food', 'fast food restaurant', 'fastener supplier', 'favela',
  'fax service', 'federal agency for technical relief', 'federal credit union',
  'federal government office', 'federal police', 'feed manufacturer', 'felt boots store',
  'fence contractor', 'fence supply store', 'fencing salon', 'fencing school',
  'feng shui consultant', 'feng shui shop', 'ferrari dealer', 'ferris wheel', 'ferry service',
  'fertility clinic', 'fertility physician', 'fertilizer supplier', 'festival', 'festival hall',
  'fiat dealer', 'fiber optic products supplier', 'fiberglass repair service',
  'fiberglass supplier', 'figurine shop', 'filipino grocery store', 'filipino restaurant',
  'film and photograph library', 'film production company', 'filtration plant',
  'finance broker', 'financial advisor', 'financial audit', 'financial consultant',
  'financial institution', 'financial planner', 'fine dining restaurant',
  'fingerprinting service', 'finishing materials supplier', 'finnish restaurant',
  'fire alarm supplier', 'fire damage restoration service',
  'fire department equipment supplier', 'fire fighters academy', 'fire protection consultant',
  'fire protection equipment supplier', 'fire protection service',
  'fire protection system supplier', 'fire station', 'firearms academy',
  'fireplace manufacturer', 'fireplace store', 'firewood supplier', 'fireworks store',
  'fireworks supplier', 'first aid station', 'fish & chips restaurant',
  'fish and chips takeaway', 'fish farm', 'fish processing', 'fish restaurant', 'fish spa',
  'fish store', 'fishing camp', 'fishing charter', 'fishing club', 'fishing pier',
  'fishing pond', 'fishing store', 'fitness center', 'fitness centre',
  'fitness equipment wholesaler', 'fitted furniture supplier', 'flag store',
  'flamenco dance store', 'flamenco school', 'flamenco theater',
  'flavours fragrances and aroma supplier', 'flea market', 'flight school', 'floating market',
  'floor refinishing service', 'floor sanding and polishing service', 'flooring contractor',
  'flooring store', 'floridian restaurant', 'florist', 'flour mill', 'flower delivery',
  'flower designer', 'flower market', 'fmcg goods wholesaler', 'fmcg manufacturer',
  'foam rubber producer', 'foam rubber supplier', 'folk high school', 'fondue restaurant',
  'food and beverage consultant', 'food and beverage exporter', 'food and drink', 'food bank',
  'food broker', 'food court', 'food machinery supplier', 'food manufacturer',
  'food manufacturing supply', 'food processing company', 'food processing equipment',
  'food producer', 'food products supplier', 'food seasoning manufacturer', 'food store',
  'foot bath', 'foot care', 'foot massage parlor', 'football club', 'football field',
  'footwear wholesaler', 'ford dealer', 'foreclosure service', 'foreign consulate',
  'foreign exchange students organization', 'foreign languages program school',
  'foreign trade consultant', 'foreman builders association', 'forensic consultant',
  'forestry service', 'forklift dealer', 'forklift rental service', 'formal wear store',
  'fortress', 'fortune telling services', 'foster care service', 'foundation', 'foundry',
  'fountain contractor', 'foursquare church', 'franconian restaurant', 'fraternal organization',
  'free clinic', 'free parking lot', 'freestyle wrestling', 'freight forwarding service',
  'french language school', 'french restaurant', 'french steakhouse restaurant',
  'fresh food market', 'fried chicken takeaway', 'friends church', 'frituur',
  'frozen dessert supplier', 'frozen food manufacturer', 'frozen food store',
  'frozen yogurt shop', 'fruit and vegetable processing', 'fruit and vegetable store',
  'fruit and vegetable wholesaler', 'fruit parlor', 'fruit wholesaler', 'fruits wholesaler',
  'fuel pump', 'fuel supplier', 'fugu restaurant', 'full dress rental service',
  'full gospel church', 'function room facility', 'funeral celebrant service',
  'funeral director', 'funeral home', 'fur coat shop', 'fur manufacturer', 'fur service',
  'furnace parts supplier', 'furnace repair service', 'furnace store',
  'furnished apartment building', 'furniture accessories', 'furniture accessories supplier',
  'furniture maker', 'furniture manufacturer', 'furniture rental service',
  'furniture repair shop', 'furniture store', 'furniture wholesaler', 'fusion restaurant',
  'futon store', 'futsal court', 'galician restaurant', 'gambling house', 'gambling instructor',
  'game store', 'garage builder', 'garage door supplier', 'garbage collection service',
  'garbage dump', 'garden', 'garden building supplier', 'garden center',
  'garden machinery supplier', 'gardener', 'garment exporter', 'gas company',
  'gas cylinders supplier', 'gas engineer', 'gas installation service', 'gas logs supplier',
  'gas shop', 'gas station', 'gasfitter', 'gasket manufacturer', 'gastroenterologist',
  'gastrointestinal surgeon', 'gastropub', 'gated community', 'gay bar', 'gay night club',
  'gay sauna', 'gazebo builder', 'gemologist', 'genealogist', 'general contractor',
  'general education school', 'general hospital', 'general practice attorney',
  'general practitioner', 'general store', 'genesis dealer', 'geological research company',
  'geological service', 'georgian restaurant', 'geotechnical engineer', 'geriatrician',
  'german language school', 'german restaurant', 'ghost town', 'gift basket store', 'gift shop',
  'gift wrap store', 'gimbap restaurant', 'girl bar', 'girls\' high school', 'girls\' hostel',
  'glass & mirror shop', 'glass block supplier', 'glass blower', 'glass cutting service',
  'glass etching service', 'glass industry', 'glass manufacturer', 'glass merchant',
  'glass repair service', 'glass shop', 'glasses repair service', 'glassware manufacturer',
  'glassware store', 'glassware wholesaler', 'glazier', 'gluten-free restaurant', 'gmc dealer',
  'goan restaurant', 'gold dealer', 'gold mining company', 'goldfish store', 'goldsmith',
  'golf cart dealer', 'golf club', 'golf course', 'golf course builder', 'golf driving range',
  'golf instructor', 'golf shop', 'gospel church', 'gourmet grocery store', 'government',
  'government college', 'government economic program', 'government hospital',
  'government office', 'government ration shop', 'government school', 'gps supplier',
  'graduate school', 'graffiti removal service', 'grain elevator', 'grammar school',
  'granite supplier', 'graphic designer', 'gravel pit', 'gravel plant', 'greek orthodox church',
  'greek restaurant', 'green energy supplier', 'greengrocer', 'greenhouse',
  'greeting card shop', 'greyhound stadium', 'grill', 'grill store', 'grocery delivery service',
  'grocery store', 'ground self defense force', 'group accommodation', 'group home',
  'grow shop', 'guardia civil', 'guardia di finanza police', 'guatemalan restaurant',
  'guest house', 'guitar instructor', 'guitar store', 'gujarati restaurant', 'gun club',
  'gun shop', 'gurudwara', 'gutter cleaning service', 'gutter service', 'gym',
  'gymnasium school', 'gymnastics center', 'gymnastics club', 'gynecologist',
  'gypsum product supplier', 'gyro restaurant', 'gyudon restaurant', 'haberdashery',
  'hair extension technician', 'hair extensions supplier', 'hair removal service',
  'hair replacement service', 'hair salon', 'hair transplantation clinic', 'hairdresser',
  'haitian restaurant', 'hakka restaurant', 'halal restaurant', 'haleem restaurant',
  'halfway house', 'ham shop', 'hamburger restaurant', 'hammam', 'hand surgeon',
  'handbags shop', 'handball club', 'handball court', 'handicapped transportation service',
  'handicraft', 'handicraft exporter', 'handicraft fair', 'handicraft museum',
  'handicraft school', 'handicrafts wholesaler', 'handyman/handywoman/handyperson',
  'hang gliding center', 'hardware shop', 'hardware store', 'harley-davidson dealer',
  'hat shop', 'haunted house', 'haute couture fashion house', 'haute french restaurant',
  'hawaiian goods store', 'hawaiian restaurant', 'hawker stall', 'hay supplier',
  'head start center', 'health', 'health and beauty shop', 'health consultant',
  'health counselor', 'health food restaurant', 'health food store', 'health insurance agency',
  'health resort', 'health spa', 'hearing aid repair service', 'hearing aid store',
  'hearing assistance earphone store', 'heart hospital', 'heating contractor',
  'heating equipment supplier', 'heating oil supplier', 'height works', 'helicopter charter',
  'helicopter tour agency', 'heliport', 'helium gas supplier', 'hematologist', 'hepatologist',
  'herb shop', 'herbal medicine store', 'herbalist', 'heritage building', 'heritage museum',
  'heritage preservation', 'heritage railroad', 'high ropes course', 'high school',
  'higher secondary school', 'highway patrol', 'hiking area', 'hiking guide', 'hindu priest',
  'hindu temple', 'hip hop dance class', 'hispanic church', 'historical landmark',
  'historical place', 'historical place museum', 'historical society', 'history museum',
  'hiv testing center', 'hoagie restaurant', 'hobby store', 'hockey club', 'hockey field',
  'hockey rink', 'hockey supply store', 'holding company', 'holiday apartment',
  'holiday apartment rental', 'holiday flat', 'holiday home', 'holiday park',
  'holistic medicine practitioner', 'home audio store', 'home automation company',
  'home builder', 'home cinema installation', 'home furniture shop', 'home goods store',
  'home health care service', 'home help', 'home help service agency', 'home improvement store',
  'home inspector', 'home insurance agency', 'home staging service', 'home theater store',
  'homekill service', 'homeless service', 'homeless shelter', 'homeopath',
  'homeopathic pharmacy', 'homeowners\' association', 'homestay', 'homewares shop',
  'honda dealer', 'honduran restaurant', 'honey farm', 'hong kong style fast food restaurant',
  'hookah bar', 'hookah store', 'horse boarding stable', 'horse breeder',
  'horse rental service', 'horse riding field', 'horse riding school', 'horse trailer dealer',
  'horse trainer', 'horseback riding service', 'horseshoe smith', 'horsestable studfarm',
  'hose supplier', 'hospice', 'hospital', 'hospital department',
  'hospital equipment and supplies', 'hospitality and tourism school',
  'hospitality high school', 'host club', 'hostel', 'hot bedstone spa', 'hot dog restaurant',
  'hot dog stand', 'hot pot restaurant', 'hot tub repair service', 'hot tub store',
  'hot water system supplier', 'hotel', 'hotel management school', 'hotel supply store',
  'house cleaning service', 'house clearance service', 'house sitter', 'house sitter agency',
  'houseboat rental service', 'household chemicals supplier', 'household goods wholesaler',
  'housing association', 'housing authority', 'housing complex', 'housing cooperative',
  'housing development', 'housing society', 'housing utility company', 'hua gong shop',
  'hua niao market place', 'hub cap supplier', 'human resource consulting',
  'hungarian restaurant', 'hunting and fishing store', 'hunting area', 'hunting club',
  'hunting preserve', 'hunting store', 'hvac contractor', 'hyderabadi restaurant',
  'hydraulic engineer', 'hydraulic equipment supplier', 'hydraulic repair service',
  'hydroelectric power plant', 'hydroponics equipment supplier', 'hygiene articles wholesaler',
  'hyperbaric medicine physician', 'hypermarket', 'hypnotherapy service', 'hyundai dealer',
  'ice cream and drink shop', 'ice cream equipment supplier', 'ice cream shop',
  'ice hockey club', 'ice skating club', 'ice skating instructor', 'ice skating rink',
  'ice supplier', 'icelandic restaurant', 'icse school', 'ikan bakar restaurant',
  'image consultant', 'imax theater', 'immigration & naturalization service',
  'immigration attorney', 'immunologist', 'impermeabilization service', 'import export company',
  'importer', 'incense supplier', 'incineration plant', 'income protection insurance agency',
  'income tax help association', 'indian grocery store', 'indian motorcycle dealer',
  'indian muslim restaurant', 'indian restaurant', 'indian sizzler restaurant',
  'indian sweets shop', 'indian takeaway', 'indonesian restaurant', 'indoor cycling',
  'indoor golf course', 'indoor lodging', 'indoor playground', 'indoor snowcenter',
  'indoor swimming pool', 'industrial chemicals wholesaler', 'industrial consultant',
  'industrial design company', 'industrial engineer', 'industrial engineers association',
  'industrial equipment supplier', 'industrial gas supplier', 'industrial real estate agency',
  'industrial spares and products wholesaler', 'industrial supermarket',
  'industrial technical engineers association', 'industrial vacuum equipment supplier',
  'infectious disease physician', 'infiniti dealer', 'information services', 'inn',
  'insolvency service', 'installation service', 'institute of geography and statistics',
  'institute of technology', 'instruction', 'instrumentation engineer', 'insulation contractor',
  'insulation materials store', 'insulator supplier', 'insurance agency', 'insurance attorney',
  'insurance broker', 'insurance company', 'intellectual property registry', 'intensivist',
  'interior architect office', 'interior construction contractor', 'interior decoration',
  'interior decorator', 'interior designer', 'interior fitting contractor',
  'interior plant service', 'internal medicine ward', 'international airport',
  'international school', 'international trade consultant', 'internet cafe',
  'internet marketing service', 'internet service provider', 'internet shop', 'internist',
  'investment bank', 'investment company', 'investment service', 'invitation printing service',
  'irish goods store', 'irish pub', 'irish restaurant', 'iron and steel store',
  'iron ware dealer', 'iron works', 'irrigation equipment supplier', 'island',
  'israeli restaurant', 'isuzu dealer', 'it support and services', 'italian grocery store',
  'italian restaurant', 'izakaya restaurant', 'jaguar dealer', 'jain temple',
  'jamaican restaurant', 'janitorial equipment supplier', 'janitorial service',
  'japanese cheap sweets shop', 'japanese confectionery shop', 'japanese curry restaurant',
  'japanese delicatessen', 'japanese grocery store', 'japanese inn',
  'japanese language instructor', 'japanese regional restaurant', 'japanese restaurant',
  'japanese steakhouse', 'japanese sweets restaurant', 'japanese-style business hotel',
  'japanized western restaurant', 'javanese restaurant', 'jazz club', 'jeans shop',
  'jeep dealer', 'jehovah\'s witness kingdom hall', 'jeweler', 'jewellery store',
  'jewelry appraiser', 'jewelry buyer', 'jewelry designer', 'jewelry engraver',
  'jewelry equipment supplier', 'jewelry exporter', 'jewelry manufacturer',
  'jewelry repair service', 'jewelry store', 'jewish restaurant', 'joiner', 'judaica store',
  'judicial auction', 'judicial scrivener', 'judo club', 'judo school', 'juice shop',
  'jujitsu school', 'junior college', 'junk dealer', 'junk removal service', 'junkyard',
  'justice department', 'jute exporter', 'jute mill', 'juvenile detention center',
  'kabaddi club', 'kaiseki restaurant', 'kalle pache restaurant', 'karaoke', 'karaoke bar',
  'karaoke equipment rental service', 'karate club', 'karate school', 'karma dealer',
  'karnataka restaurant', 'kashmiri restaurant', 'kawasaki motorcycle dealer',
  'kazakhstani restaurant', 'kebab shop', 'kennel', 'kerala restaurant', 'kerosene supplier',
  'key duplication service', 'kia dealer', 'kickboxing school', 'kilt shop and hire',
  'kimono store', 'kindergarten', 'kinesiologist', 'kinesiotherapist', 'kiosk',
  'kitchen furniture store', 'kitchen remodeler', 'kitchen renovator', 'kitchen supply store',
  'kite shop', 'knife store', 'knit shop', 'knitting instructor', 'knitwear manufacturer',
  'kofta restaurant', 'konkani restaurant', 'korean barbecue restaurant',
  'korean beef restaurant', 'korean church', 'korean grocery store', 'korean restaurant',
  'korean rib restaurant', 'koshari restaurant', 'kosher grocery store', 'kosher restaurant',
  'kung fu school', 'kushiage and kushikatsu restaurant', 'kushiyaki restaurant',
  'labor relations attorney', 'labor union', 'laboratory', 'laboratory equipment supplier',
  'ladder supplier', 'ladies\' clothes shop', 'lake', 'lamborghini dealer',
  'laminating equipment supplier', 'lamination service', 'lamp repair service',
  'lamp shade supplier', 'lancia dealer', 'land allotment', 'land planning authority',
  'land reform institute', 'land rover dealer', 'land surveying office', 'land surveyor',
  'landscape architect', 'landscape designer', 'landscape gardener',
  'landscape lighting designer', 'landscaper', 'landscaping supply store', 'language school',
  'laotian restaurant', 'lapidary', 'laser cutting service', 'laser equipment supplier',
  'laser hair removal service', 'laser tag center', 'lasik surgeon',
  'latin american restaurant', 'laundromat', 'laundry', 'laundry service', 'law book store',
  'law firm', 'law library', 'law school', 'lawn bowls club', 'lawn care service',
  'lawn equipment rental service', 'lawn irrigation equipment supplier',
  'lawn mower repair service', 'lawn mower store', 'lawn sprinkler system contractor', 'lawyer',
  'lawyers association', 'leagues club', 'learner driver training area', 'learning center',
  'leasing service', 'leather cleaning service', 'leather coats store', 'leather exporter',
  'leather goods manufacturer', 'leather goods store', 'leather goods supplier',
  'leather goods wholesaler', 'leather repair service', 'leather wholesaler',
  'lebanese restaurant', 'lechon restaurant', 'legal affairs bureau', 'legal services',
  'leisure centre', 'lesbian bar', 'lexus dealer', 'library', 'license bureau',
  'license plate frames supplier', 'lido', 'life coach', 'life insurance agency',
  'light bulb supplier', 'lighting consultant', 'lighting contractor', 'lighting manufacturer',
  'lighting products wholesaler', 'lighting store', 'ligurian restaurant', 'limousine service',
  'line marking service', 'linens store', 'lingerie manufacturer', 'lingerie store',
  'lingerie wholesaler', 'linoleum store', 'liquidator', 'liquor store', 'literacy program',
  'lithuanian restaurant', 'little league club', 'little league field', 'live music bar',
  'live music venue', 'livery company', 'livestock auction house', 'livestock breeder',
  'livestock dealer', 'livestock producer', 'loan agency', 'local government office',
  'local history museum', 'local medical services', 'lock store', 'locks supplier', 'locksmith',
  'lodge', 'lodging', 'log cabins', 'log home builder', 'logging contractor',
  'logistics service', 'lombardian restaurant', 'loss adjuster', 'lost property office',
  'lottery retailer', 'lottery shop', 'lounge', 'love hotel', 'low income housing program',
  'lpg conversion', 'luggage repair service', 'luggage storage facility', 'luggage store',
  'luggage wholesaler', 'lumber store', 'lunch restaurant', 'lutheran church', 'lyceum',
  'lymph drainage therapist', 'machine construction', 'machine knife supplier',
  'machine maintenance service', 'machine repair service', 'machine shop', 'machine workshop',
  'machinery parts manufacturer', 'machining manufacturer', 'macrobiotic restaurant',
  'madrilian restaurant', 'magazine store', 'magic store', 'magician', 'mailbox rental service',
  'mailbox supplier', 'mailing machine supplier', 'mailing service', 'main customs office',
  'majorcan restaurant', 'make-up artist', 'makerspace', 'malaysian restaurant',
  'maltese restaurant', 'mammography service', 'manado restaurant', 'management school',
  'mandarin restaurant', 'manor house', 'manufactured home transporter', 'manufacturer',
  'maori organization', 'map store', 'mapping service', 'marae', 'marathi restaurant',
  'marble contractor', 'marble supplier', 'marche restaurant', 'marina', 'marine engineer',
  'marine self defense force', 'marine supply store', 'marine surveyor', 'maritime museum',
  'market', 'market researcher', 'marketing agency', 'marketing consultant',
  'marquee hire service', 'marriage celebrant', 'marriage license bureau',
  'marriage or relationship counselor', 'martial arts club', 'martial arts school',
  'martial arts supply store', 'maserati dealer', 'masonry contractor', 'masonry supply store',
  'massage parlor', 'massage school', 'massage service', 'massage spa', 'massage supply store',
  'massage therapist', 'match box manufacturer', 'material handling equipment supplier',
  'maternity hospital', 'maternity store', 'mathematics school', 'mattress store',
  'mausoleum builder', 'maybach dealer', 'mazda dealer', 'mclaren dealer', 'meal delivery',
  'measuring instruments supplier', 'meat dish restaurant', 'meat packer', 'meat processor',
  'meat products store', 'meat wholesaler', 'mechanic', 'mechanical contractor',
  'mechanical engineer', 'mechanical plant', 'media company', 'media consultant', 'media house',
  'mediation service', 'medical billing service', 'medical book store', 'medical center',
  'medical centre', 'medical certificate service', 'medical clinic',
  'medical diagnostic imaging center', 'medical equipment manufacturer',
  'medical equipment supplier', 'medical examiner', 'medical group', 'medical laboratory',
  'medical lawyer', 'medical office', 'medical school', 'medical spa', 'medical supply store',
  'medical technology manufacturer', 'medical transcription service', 'medicine exporter',
  'meditation center', 'meditation instructor', 'mediterranean restaurant',
  'meeting planning service', 'mehandi class', 'mehndi designer', 'memorial', 'memorial estate',
  'memorial park', 'men\'s clothes shop', 'men\'s clothing store', 'men\'s health physician',
  'men\'s tailor', 'mennonite church', 'mens tailor', 'mental health clinic',
  'mental health service', 'mercantile development', 'mercedes-benz dealer',
  'messianic synagogue', 'metal construction company', 'metal detecting equipment supplier',
  'metal fabricator', 'metal finisher', 'metal heat treating service',
  'metal industry suppliers', 'metal machinery supplier', 'metal polishing service',
  'metal processing company', 'metal stamping service', 'metal supplier', 'metal working shop',
  'metal workshop', 'metallurgy company', 'metalware dealer', 'metalware producer', 'metalwork',
  'metaphysical supply store', 'methodist church', 'metropolitan train company',
  'mexican goods store', 'mexican grocery store', 'mexican restaurant',
  'mexican torta restaurant', 'meyhane', 'mg dealer', 'microwave oven repair service',
  'middle eastern restaurant', 'middle school', 'midwife', 'military base', 'military board',
  'military cemetery', 'military hospital', 'military recruiting office', 'military school',
  'military town', 'milk delivery service', 'mill', 'millwork shop', 'mine',
  'mineral water company', 'mini dealer', 'miniature golf course', 'miniatures store',
  'minibus taxi service', 'mining company', 'mining consultant', 'mining engineer',
  'mining equipment', 'ministry of education', 'mirror shop', 'miso cutlet restaurant',
  'missing persons organization', 'mission', 'mitsubishi dealer', 'mobile caterer',
  'mobile disco service', 'mobile home dealer', 'mobile home park', 'mobile home rental agency',
  'mobile home supply store', 'mobile money agent', 'mobile network operator',
  'mobile phone repair shop', 'mobile phone shop', 'mobility equipment supplier',
  'model car play area', 'model design company', 'model portfolio studio', 'model shop',
  'model train store', 'modeling agency', 'modeling school', 'modern art museum',
  'modern british restaurant', 'modern european restaurant', 'modern french restaurant',
  'modern indian restaurant', 'modern izakaya restaurant', 'modular home builder',
  'modular home dealer', 'mohel', 'mold maker', 'molding supplier', 'momo restaurant',
  'monastery', 'money order service', 'money transfer service', 'mongolian barbecue restaurant',
  'monogramming service', 'montessori school', 'monument', 'monument maker', 'moped dealer',
  'moravian church', 'moroccan restaurant', 'mortgage broker', 'mortgage lender', 'mortuary',
  'mosque', 'motel', 'motor scooter dealer', 'motor scooter repair shop',
  'motor vehicle dealer', 'motorcycle dealer', 'motorcycle driving school',
  'motorcycle insurance agency', 'motorcycle parts store', 'motorcycle rental agency',
  'motorcycle repair shop', 'motorcycle shop', 'motoring club', 'motorsports store',
  'mountain cabin', 'mountain cable car', 'mountain peak', 'mountaineering class', 'mover',
  'movie rental kiosk', 'movie rental store', 'movie studio', 'movie theater',
  'moving and storage service', 'moving company', 'moving supply store', 'mri center',
  'muay thai boxing gym', 'muffler shop', 'mughlai restaurant', 'mulch supplier',
  'multimedia and electronic book publisher', 'municipal administration office',
  'municipal department of tourism', 'municipal guard', 'murtabak restaurant', 'musalla',
  'museum', 'museum of space history', 'museum of zoology', 'music box store', 'music college',
  'music conservatory', 'music instructor', 'music management and promotion', 'music producer',
  'music publisher', 'music school', 'music store', 'musical club',
  'musical instrument manufacturer', 'musical instrument rental service',
  'musical instrument repair shop', 'musical instrument store', 'musician',
  'musician and composer', 'mutton barbecue restaurant', 'nail salon', 'nasi goreng restaurant',
  'nasi restaurant', 'nasi uduk restaurant', 'national forest', 'national library',
  'national museum', 'national park', 'national reserve', 'native american goods store',
  'native american restaurant', 'natural goods store', 'natural history museum',
  'natural rock climbing area', 'natural stone exporter', 'natural stone supplier',
  'natural stone wholesaler', 'nature preserve', 'naturopathic practitioner', 'naval base',
  'navarraise restaurant', 'neapolitan restaurant', 'needlework shop', 'neon sign shop',
  'neonatal physician', 'nepalese restaurant', 'nephrologist', 'netball club', 'neurologist',
  'neurophysiologist', 'neuropsychologist', 'neurosurgeon', 'new age church',
  'new american restaurant', 'new england restaurant', 'new zealand restaurant', 'news service',
  'newspaper distribution service', 'newspaper publisher', 'newsstand', 'nicaraguan restaurant',
  'night club', 'night market', 'nissan dealer', 'non smoking holiday home',
  'non vegetarian restaurant', 'non-denominational church', 'non-governmental organization',
  'non-profit organization', 'noodle shop', 'north african restaurant',
  'north eastern indian restaurant', 'north indian restaurant', 'northern italian restaurant',
  'norwegian restaurant', 'notaries association', 'notary public', 'notions store',
  'novelties wholesaler', 'novelty store', 'nuclear power company', 'nuclear power plant',
  'nudist club', 'nudist park', 'nuevo latino restaurant', 'numerologist', 'nurse practitioner',
  'nursery school', 'nursing agency', 'nursing association', 'nursing home', 'nursing school',
  'nut store', 'nutritionist', 'nyonya restaurant', 'oaxacan restaurant', 'observation deck',
  'observatory', 'obstetrician-gynecologist', 'occupational health service',
  'occupational medical physician', 'occupational safety and health', 'occupational therapist',
  'oden restaurant', 'odia restaurant', 'off roading area', 'off track betting shop',
  'offal barbecue restaurant', 'offal pot cooking restaurant', 'office',
  'office accessories wholesaler', 'office equipment rental service',
  'office equipment repair service', 'office equipment supplier', 'office furniture store',
  'office refurbishment service', 'office space rental agency', 'office supply store',
  'office supply wholesaler', 'offset printing service', 'oil & natural gas company',
  'oil and gas exploration service', 'oil change service', 'oil field equipment supplier',
  'oil refinery', 'oilfield', 'okonomiyaki restaurant', 'oldsmobile dealer',
  'olive oil bottling company', 'olive oil cooperative', 'olive oil manufacturer', 'oncologist',
  'onsen', 'opel dealer', 'open air museum', 'open university', 'opera company', 'opera house',
  'ophthalmologist', 'ophthalmology clinic', 'optical instrument repair service',
  'optical products manufacturer', 'optical wholesaler', 'optician', 'optometrist',
  'oral and maxillofacial surgeon', 'oral surgeon', 'orchard', 'orchestra', 'orchid farm',
  'orchid grower', 'organ donation and tissue bank', 'organic drug store', 'organic farm',
  'organic food store', 'organic restaurant', 'organic shop', 'oriental goods store',
  'oriental medicine clinic', 'oriental medicine store', 'oriental rug store', 'orphanage',
  'orthodontist', 'orthodox church', 'orthodox synagogue', 'orthopedic clinic',
  'orthopedic shoe store', 'orthopedic supplies store', 'orthopedic surgeon', 'orthoptist',
  'orthotics & prosthetics service', 'osteopath', 'otolaryngologist', 'otolaryngology clinic',
  'outboard motor store', 'outdoor activity organiser', 'outdoor bath',
  'outdoor clothing and equipment shop', 'outdoor equestrian facility',
  'outdoor furniture store', 'outdoor sports store', 'outdoor swimming pool', 'outerwear store',
  'outlet mall', 'outlet store', 'oxygen cocktail spot', 'oxygen equipment supplier',
  'oyster bar restaurant', 'oyster supplier', 'paan shop', 'pacific rim restaurant',
  'package locker', 'packaging company', 'packaging supply store', 'padang restaurant',
  'padel club', 'padel court', 'pagoda', 'pain control clinic', 'pain management physician',
  'paint manufacturer', 'paint store', 'paint stripping service', 'paintball center',
  'paintball store', 'painter', 'painter and decorator', 'painting', 'painting lessons',
  'painting studio', 'paintings store', 'paisa restaurant', 'pakistani restaurant',
  'palatine restaurant', 'pallet supplier', 'pan-asian restaurant', 'pancake restaurant',
  'panipuri shop', 'paper bag supplier', 'paper distributor', 'paper exporter', 'paper mill',
  'paper shredding machine supplier', 'paper store', 'paraguayan restaurant',
  'paralegal services provider', 'parapharmacy', 'parish', 'park', 'park and garden',
  'park and ride', 'parking', 'parking garage', 'parking grounds', 'parking lot',
  'parking lot for bicycles', 'parking lot for motorcycles', 'parkour spot', 'parochial school',
  'parsi restaurant', 'parsi temple', 'party equipment rental service', 'party planner',
  'party store', 'passport agent', 'passport office', 'passport photo processor', 'pasta shop',
  'pastry shop', 'patent attorney', 'patent office', 'paternity testing service', 'pathologist',
  'patients support association', 'patio enclosure supplier', 'patisserie', 'paving contractor',
  'paving materials supplier', 'pawn shop', 'pay by weight restaurant', 'payroll service',
  'pecel lele restaurant', 'pedestrian zone', 'pediatric cardiologist', 'pediatric clinic',
  'pediatric dentist', 'pediatric dermatologist', 'pediatric endocrinologist',
  'pediatric gastroenterologist', 'pediatric hematologist', 'pediatric nephrologist',
  'pediatric neurologist', 'pediatric oncologist', 'pediatric ophthalmologist',
  'pediatric pulmonologist', 'pediatric rheumatologist', 'pediatric surgeon',
  'pediatric urologist', 'pediatrician', 'pedorthist', 'pempek restaurant', 'pen store',
  'pennsylvania dutch restaurant', 'pension office', 'pentecostal church',
  'performing arts group', 'performing arts theater', 'perfume store', 'perinatal center',
  'periodontist', 'permanent make-up clinic', 'persian restaurant', 'personal chef service',
  'personal injury attorney', 'personal injury lawyer', 'personal trainer',
  'personal watercraft dealer', 'peruvian restaurant', 'pest control service',
  'pet adoption service', 'pet boarding service', 'pet care service', 'pet cemetery',
  'pet food and animal feeds', 'pet groomer', 'pet moving service', 'pet shop', 'pet sitter',
  'pet store', 'pet supply store', 'pet trainer', 'petrol station',
  'petroleum products company', 'peugeot dealer', 'pharmaceutical company',
  'pharmaceutical lab', 'pharmaceutical products wholesaler', 'pharmacy', 'philharmonic hall',
  'pho restaurant', 'phone repair service', 'photo agency', 'photo booth', 'photo lab',
  'photo restoration service', 'photo shop', 'photographer', 'photography class',
  'photography school', 'photography service', 'photography studio', 'physiatrist',
  'physical examination center', 'physical fitness program', 'physical rehabilitation center',
  'physical therapist', 'physical therapy clinic', 'physician assistant',
  'physician referral service', 'physiotherapist', 'physiotherapy center',
  'physiotherapy equipment supplier', 'piadina restaurant', 'piano bar', 'piano instructor',
  'piano maker', 'piano moving service', 'piano repair service', 'piano store',
  'piano tuning service', 'pick your own farm produce', 'pickleball court', 'picnic ground',
  'picture frame shop', 'pie shop', 'piedmontese restaurant', 'pig farm', 'pilaf restaurant',
  'pilates studio', 'pilgrim hostel', 'pinball machine supplier', 'pine furniture shop',
  'pipe supplier', 'pizza delivery', 'pizza restaurant', 'pizza takeaway', 'pizza takeout',
  'place of worship', 'planetarium', 'plant and machinery hire', 'plant nursery',
  'plast window store', 'plasterer', 'plastic bag supplier', 'plastic bags wholesaler',
  'plastic fabrication company', 'plastic injection molding service',
  'plastic products supplier', 'plastic products wholesaler', 'plastic resin manufacturer',
  'plastic surgeon', 'plastic surgery clinic', 'plastic wholesaler', 'plating service',
  'playground', 'playground equipment supplier', 'playgroup', 'plumber',
  'plumbing supply store', 'plus size clothing store', 'plywood supplier',
  'pneumatic tools supplier', 'podiatrist', 'poke bar', 'police academy', 'police department',
  'police supply store', 'polish restaurant', 'political party office', 'polo club',
  'polygraph service', 'polymer supplier', 'polynesian restaurant', 'polytechnic institute',
  'polythene and plastic sheeting supplier', 'pond contractor', 'pond fish supplier',
  'pond supply store', 'pontiac dealer', 'pony club', 'pony ride service', 'pool billard club',
  'pool cleaning service', 'pool hall', 'popcorn store', 'porridge restaurant',
  'porsche dealer', 'port authority', 'port operating company',
  'portable building manufacturer', 'portable toilet supplier', 'portrait studio',
  'portuguese restaurant', 'post office', 'postal code', 'poster store', 'pottery classes',
  'pottery manufacturer', 'pottery store', 'poultry farm', 'poultry store',
  'powder coating service', 'power plant consultant', 'power plant equipment supplier',
  'power station', 'powersports vehicle dealer', 'pozole restaurant',
  'practitioner service location', 'prawn fishing', 'pre-school', 'precision engineer',
  'pregnancy care center', 'preparatory school', 'presbyterian church', 'preschool',
  'press advisory', 'pressure washing service', 'pretzel store', 'priest', 'primary school',
  'print shop', 'printed music publisher', 'printer ink refill store', 'printer repair service',
  'printing equipment supplier', 'prison', 'private college', 'private educational institution',
  'private equity firm', 'private golf course', 'private hospital', 'private investigator',
  'private sector bank', 'private tutor', 'private university', 'probation office',
  'process server', 'proctologist', 'produce market', 'produce wholesaler',
  'professional and hobby associations', 'professional association', 'professional organizer',
  'promenade', 'promotional products supplier', 'propane supplier', 'propeller shop',
  'property administration service', 'property consultant', 'property developer',
  'property investment', 'property investment company', 'property maintenance',
  'property management company', 'prosthodontist', 'protected area',
  'protective clothing supplier', 'protestant church', 'provence restaurant',
  'psychiatric hospital', 'psychiatrist', 'psychic', 'psychoanalyst', 'psychologist',
  'psychomotor therapist', 'psychoneurological specialized clinic', 'psychopedagogy clinic',
  'psychosomatic medical practitioner', 'psychotherapist', 'pub', 'public bath',
  'public bathroom', 'public beach', 'public defender\'s office',
  'public educational institution', 'public golf course', 'public health department',
  'public housing', 'public library', 'public medical center', 'public parking space',
  'public prosecutors office', 'public relations firm', 'public safety office', 'public sauna',
  'public sector bank', 'public swimming pool', 'public university', 'public works department',
  'publisher', 'pueblan restaurant', 'puerto rican restaurant', 'pulmonologist',
  'pump supplier', 'pumpkin patch', 'punjabi restaurant', 'puppet theater',
  'pvc windows supplier', 'pyrotechnician', 'qing fang market place', 'quaker church',
  'quantity surveyor', 'quarry', 'quilt shop', 'race car dealer', 'racing car parts store',
  'raclette restaurant', 'racquetball club', 'radiator repair service', 'radiator shop',
  'radio broadcaster', 'radiologist', 'radiotherapist', 'raft trip outfitter', 'rafting',
  'rail museum', 'railing contractor', 'railroad company', 'railroad contractor',
  'railroad equipment supplier', 'railroad ties supplier', 'railway services',
  'rainwater tank supplier', 'rajasthani restaurant', 'ram dealer', 'ramen restaurant', 'ranch',
  'rare book store', 'raw food restaurant', 'ready mix concrete supplier', 'real estate',
  'real estate agency', 'real estate agent', 'real estate appraiser', 'real estate attorney',
  'real estate auctioneer', 'real estate consultant', 'real estate developer',
  'real estate rental agency', 'real estate school', 'real estate surveyor', 'record company',
  'record store', 'recording studio', 'records storage facility', 'recreation',
  'recreation center', 'recreational vehicle rental agency', 'recruiter', 'rectory',
  'recycling', 'recycling center', 'recycling drop-off location', 'reenactment site',
  'reflexologist', 'reform synagogue', 'reformed church', 'refrigerated transport service',
  'refrigerator repair service', 'refrigerator store', 'refugee camp', 'regional airport',
  'regional council', 'regional government office', 'registered general nurse',
  'registration office', 'registry office', 'rehabilitation center', 'rehearsal studio',
  'reiki therapist', 'religious book store', 'religious destination', 'religious goods store',
  'religious institution', 'religious lodging', 'religious organization', 'religious school',
  'remodeler', 'renault dealer', 'renovation contractor', 'renter\'s insurance agency',
  'repair service', 'reproductive health clinic', 'reptile store',
  'research and product development', 'research engineer', 'research foundation',
  'research institute', 'residential building', 'residential college', 'residents association',
  'resort hotel', 'rest stop', 'restaurant', 'restaurant or cafe', 'restaurant supply store',
  'resume service', 'retail space rental agency', 'retaining wall supplier',
  'retirement community', 'retirement home', 'retreat center', 'rheumatologist',
  'rice cake shop', 'rice cracker shop', 'rice mill', 'rice restaurant', 'rice shop',
  'rice wholesaler', 'river', 'river port', 'road construction company',
  'road construction machine repair service', 'road cycling', 'road safety town',
  'roads ports and canals engineers association', 'rock climbing', 'rock climbing gym',
  'rock climbing instructor', 'rock music club', 'rock shop', 'rodeo',
  'rolled metal products supplier', 'roller coaster', 'roller skating club',
  'roller skating rink', 'roman restaurant', 'romanian restaurant', 'roofing contractor',
  'roofing service', 'roofing supply store', 'roommate referral service', 'rowing area',
  'rowing club', 'rsl club', 'rubber products supplier', 'rubber stamp store', 'rug store',
  'rugby', 'rugby club', 'rugby field', 'rugby league club', 'rugby store', 'running store',
  'russian grocery store', 'russian orthodox church', 'russian restaurant',
  'rustic furniture store', 'rv dealer', 'rv detailing service', 'rv park', 'rv repair shop',
  'rv storage facility', 'rv supply store', 'saab dealer', 'sacem', 'saddlery',
  'safe & vault shop', 'safety equipment supplier', 'sailing club', 'sailing event area',
  'sailing school', 'sailmaker', 'sake brewery', 'salad shop', 'salsa bar', 'salsa classes',
  'salvadoran restaurant', 'salvage dealer', 'salvage yard', 'samba school', 'sambo school',
  'sambodrome', 'sand & gravel supplier', 'sand and gravel supplier', 'sand plant',
  'sandblasting service', 'sandwich shop', 'sanitary inspection', 'sanitation service',
  'sardinian restaurant', 'saree shop', 'sashimi restaurant', 'satay restaurant',
  'satellite communication service', 'saturn dealer', 'sauna', 'sauna club', 'sauna store',
  'savings bank', 'saw mill', 'saw sharpening service', 'scaffolding rental service',
  'scale model club', 'scale repair service', 'scale supplier', 'scandinavian restaurant',
  'scenic spot', 'scenography company', 'school', 'school administration office',
  'school bus service', 'school cafeteria', 'school center', 'school district office',
  'school for the deaf', 'school house', 'school supply store', 'science museum',
  'scientific equipment supplier', 'scooter rental service', 'scooter repair shop',
  'scottish restaurant', 'scout hall', 'scout home', 'scouting', 'scrap metal dealer',
  'scrapbooking store', 'screen printer', 'screen printing shop',
  'screen printing supply store', 'screen repair service', 'screen store', 'screw supplier',
  'scuba instructor', 'scuba tour agency', 'sculptor', 'sculpture', 'sculpture museum',
  'seafood farm', 'seafood market', 'seafood restaurant', 'seafood wholesaler', 'seal shop',
  'seaplane base', 'seasonal goods store', 'seat dealer', 'seblak restaurant',
  'second hand store', 'secondary school', 'security guard service', 'security service',
  'security system installation service', 'security system supplier', 'seed supplier', 'seitai',
  'self defense school', 'self service car wash', 'self service health station',
  'self service restaurant', 'self storage facility', 'self-catering accommodation',
  'self-storage facility', 'semi conductor supplier', 'seminary', 'senior citizen center',
  'senior high school', 'septic system service', 'serbian restaurant', 'service establishment',
  'serviced accommodation', 'serviced apartment', 'services', 'seventh-day adventist church',
  'sewage disposal service', 'sewage treatment plant', 'sewing company',
  'sewing machine repair service', 'sewing machine store', 'sewing shop', 'sexologist',
  'seychelles restaurant', 'sfiha restaurant', 'shanghainese restaurant', 'sharpening service',
  'shawarma restaurant', 'shed builder', 'sheep shearer',
  'sheepskin and wool products supplier', 'sheet metal contractor', 'sheet music store',
  'shelter', 'sheltered housing', 'shelving store', 'shinto shrine',
  'shipbuilding and repair company', 'shipping and mailing service', 'shipping company',
  'shipping equipment industry', 'shipping service', 'shipyard', 'shochu brewery',
  'shoe factory', 'shoe repair shop', 'shoe shining service', 'shoe shop', 'shoe store',
  'shogi lesson', 'shooting event area', 'shooting range', 'shop',
  'shop supermarket furniture store', 'shopfitter', 'shopping centre', 'shopping mall',
  'short term apartment rental agency', 'shower door shop', 'showroom', 'shredding service',
  'shrimp farm', 'shrine', 'sichuan restaurant', 'sicilian restaurant', 'siding contractor',
  'sightseeing tour agency', 'sign shop', 'signwriting service', 'silk plant shop',
  'silk store', 'silversmith', 'singaporean restaurant', 'singing telegram service',
  'single sex secondary school', 'singles organization', 'sixth form college',
  'skate sharpening service', 'skate shop', 'skateboard shop', 'skatepark',
  'skating instructor', 'skeet shooting range', 'ski club', 'ski rental service',
  'ski repair service', 'ski resort', 'ski school', 'ski shop', 'skin care clinic',
  'skin care products vending machine', 'skittle club', 'skoda dealer', 'skydiving center',
  'skylight contractor', 'slaughterhouse', 'sleep clinic', 'small appliance repair service',
  'small claims assistance service', 'small engine repair service', 'small plates restaurant',
  'smart car dealer', 'smart dealer', 'smart shop', 'smog inspection station', 'smoke shop',
  'snack bar', 'snow removal service', 'snowboard rental service', 'snowboard shop',
  'snowmobile dealer', 'snowmobile rental service', 'soapland', 'soba noodle shop',
  'soccer club', 'soccer field', 'soccer practice', 'soccer store', 'social club',
  'social security attorney', 'social security financial department', 'social security office',
  'social services organization', 'social welfare center', 'social worker',
  'societe de flocage', 'sod supplier', 'sofa store', 'soft drinks shop', 'softball club',
  'softball field', 'software company', 'software training institute', 'soil testing service',
  'solar energy company', 'solar energy equipment supplier', 'solar energy system service',
  'solar hot water system supplier', 'solar panel maintenance service',
  'solar photovoltaic power plant', 'solid fuel company', 'solid waste engineer',
  'soondae restaurant', 'soto ayam restaurant', 'soto restaurant', 'soul food restaurant',
  'soup kitchen', 'soup restaurant', 'soup shop', 'south african restaurant',
  'south american restaurant', 'south asian restaurant', 'south east asian restaurant',
  'south indian restaurant', 'south sulawesi restaurant', 'southeast asian restaurant',
  'southern italian restaurant', 'southern restaurant (us)', 'souvenir manufacturer',
  'souvenir store', 'soy sauce maker', 'spa', 'spa and health club', 'spa garden',
  'space of remembrance', 'spanish restaurant', 'special education school', 'special educator',
  'specialized clinic', 'specialized hospital', 'speech pathologist', 'sperm bank',
  'spice exporter', 'spice store', 'spice wholesaler', 'spices exporter', 'spiritist center',
  'sport tour agency', 'sporting goods store', 'sports', 'sports accessories wholesaler',
  'sports activity location', 'sports bar', 'sports card store', 'sports club',
  'sports complex', 'sports equipment rental service', 'sports injury clinic',
  'sports massage therapist', 'sports medicine clinic', 'sports medicine physician',
  'sports memorabilia store', 'sports nutrition store', 'sports school', 'sportswear store',
  'sportwear manufacturer', 'spring supplier', 'squash club', 'squash court',
  'sri lankan restaurant', 'stable', 'stadium', 'stage', 'stage lighting equipment supplier',
  'stained glass studio', 'stainless steel plant', 'stair contractor',
  'stall installation service', 'stamp collectors club', 'stamp shop', 'stand bar',
  'staple food package', 'state archive', 'state employment department',
  'state government office', 'state liquor store', 'state office of education',
  'state owned farm', 'state park', 'state parliament', 'state police',
  'stationery manufacturer', 'stationery store', 'stationery wholesaler', 'statuary',
  'std clinic', 'std testing service', 'steak house', 'steamboat restaurant',
  'steamed bun shop', 'steel construction company', 'steel distributor', 'steel erector',
  'steel fabricator', 'steel framework contractor', 'steelwork design service',
  'stereo rental store', 'stereo repair service', 'sticker manufacturer', 'stitching class',
  'stock broker', 'stock exchange building', 'stone carving', 'stone cutter', 'stone supplier',
  'storage facility', 'store', 'store equipment supplier', 'stores and shopping',
  'structural engineer', 'stucco contractor', 'student career counseling office',
  'student dormitory', 'student housing center', 'student union',
  'students parents association', 'students support association', 'study at home school',
  'studying center', 'stylist', 'subaru dealer', 'suburban train line', 'subway station',
  'sugar factory', 'sugar shack', 'sukiyaki and shabu shabu restaurant', 'sukiyaki restaurant',
  'summer camp organizer', 'summer toboggan run', 'sunblind supplier', 'sundae restaurant',
  'sundanese restaurant', 'sunglasses store', 'sunroom contractor', 'super public bath',
  'superannuation consultant', 'superfund site', 'supermarket',
  'supplementary educational institute', 'support group', 'surf lifesaving club', 'surf school',
  'surf shop', 'surgeon', 'surgical center', 'surgical oncologist',
  'surgical products wholesaler', 'surgical supply store', 'surinamese restaurant',
  'surplus store', 'surveyor', 'sushi restaurant', 'sushi takeaway', 'suzuki dealer',
  'suzuki motorcycle dealer', 'swabian restaurant', 'swedish restaurant',
  'sweets and dessert buffet', 'swim club', 'swimming basin', 'swimming competition',
  'swimming facility', 'swimming instructor', 'swimming lake', 'swimming pool',
  'swimming pool contractor', 'swimming pool repair service', 'swimming pool supply store',
  'swimming school', 'swimwear store', 'swiss restaurant', 'synagogue',
  'syokudo and teishoku restaurant', 'syrian restaurant', 't-shirt store',
  'tabascan restaurant', 'table tennis club', 'table tennis facility',
  'table tennis supply store', 'tacaca restaurant', 'tack shop', 'taco restaurant',
  'taekwondo school', 'tai chi school', 'tailor', 'taiwanese restaurant', 'takeaway',
  'takeout restaurant', 'takoyaki restaurant', 'talent agency', 'tamale shop', 'tannery',
  'tanning salon', 'taoist temple', 'tapas bar', 'tapas restaurant', 'tata motors dealer',
  'tatami store', 'tattoo and piercing shop', 'tattoo artist', 'tattoo removal service',
  'tattoo shop', 'tax assessor', 'tax attorney', 'tax collector\'s office', 'tax consultant',
  'tax department', 'tax preparation', 'tax preparation service', 'taxi service', 'taxi stand',
  'taxicab stand', 'taxidermist', 'tb clinic', 'tea and coffee shop', 'tea exporter',
  'tea house', 'tea manufacturer', 'tea market place', 'tea store', 'tea wholesaler',
  'teachers college', 'technical school', 'technical university', 'technology museum',
  'technology park', 'teeth whitening service', 'tegal restaurant', 'telecommunication school',
  'telecommunications', 'telecommunications contractor', 'telecommunications engineer',
  'telecommunications equipment supplier', 'telecommunications service provider',
  'telemarketing service', 'telephone answering service', 'telephone company',
  'telephone exchange', 'telescope store', 'television repair service', 'television station',
  'temaki restaurant', 'temp agency', 'tempura restaurant', 'tenant ownership', 'tennis club',
  'tennis court', 'tennis court construction company', 'tennis instructor', 'tennis store',
  'tent rental service', 'teppanyaki restaurant', 'tesla showroom', 'tex-mex restaurant',
  'textile engineer', 'textile exporter', 'textile merchant', 'textile mill',
  'thai massage therapist', 'thai restaurant', 'theater company', 'theater production',
  'theater supply store', 'theatrical costume supplier', 'theme park', 'thermal baths',
  'thread supplier', 'threads and yarns wholesaler', 'thrift store', 'thuringian restaurant',
  'tibetan restaurant', 'tiffin center', 'tiki bar', 'tile cleaning service', 'tile contractor',
  'tile manufacturer', 'tile store', 'timeshare agency', 'tire repair shop', 'tire service',
  'tire shop', 'title company', 'toast restaurant', 'tobacco shop', 'tobacco supplier',
  'tofu restaurant', 'tofu shop', 'toiletries store', 'toll station',
  'toner cartridge supplier', 'tongue restaurant', 'tonkatsu restaurant', 'tool & die shop',
  'tool manufacturer', 'tool rental service', 'tool repair shop', 'tool store',
  'tool wholesaler', 'toolroom', 'topography company', 'topsoil supplier', 'tortilla shop',
  'tour agency', 'tour operator', 'tourist attraction', 'tourist information center',
  'towing equipment provider', 'towing service', 'townhouse complex', 'toy library',
  'toy manufacturer', 'toy museum', 'toy store', 'toyota dealer', 'tractor dealer',
  'tractor repair shop', 'trade fair construction company', 'trade school',
  'trading card store', 'trading company', 'traditional american restaurant',
  'traditional costume club', 'traditional kostume store', 'traditional market',
  'traditional teahouse', 'traffic officer', 'trailer dealer', 'trailer manufacturer',
  'trailer rental service', 'trailer repair shop', 'trailer supply store', 'train depot',
  'train repairing center', 'train station', 'train ticket agency', 'train yard',
  'training center', 'training centre', 'training consultant', 'training provider', 'tram stop',
  'transcription service', 'transit depot', 'transit station', 'transit stop',
  'translation service', 'transmission shop', 'transplant surgeon', 'transport hub',
  'transportation escort service', 'transportation service', 'travel', 'travel agency',
  'travel agent', 'travel clinic', 'travel lounge', 'tree farm', 'tree service',
  'trial attorney', 'tribal headquarters', 'triumph motorcycle dealer', 'trolleybus stop',
  'trophy shop', 'tropical fish store', 'truck accessories store', 'truck dealer',
  'truck driving school', 'truck farmer', 'truck parts supplier', 'truck rental agency',
  'truck repair shop', 'truck stop', 'truck topper supplier', 'trucking company',
  'truss manufacturer', 'trust bank', 'tsukigime parking lot', 'tune up supplier',
  'tunisian restaurant', 'turf supplier', 'turkish restaurant', 'turkmen restaurant', 'turnery',
  'tuscan restaurant', 'tutoring service', 'tuxedo shop', 'typewriter repair service',
  'typewriter supplier', 'typing service', 'tyre manufacturer', 'udon noodle restaurant',
  'ukrainian restaurant', 'unagi restaurant', 'underwear store', 'unemployment office',
  'unfinished furniture store', 'uniform store', 'unitarian universalist church',
  'united church of canada', 'united church of christ', 'united methodist church',
  'united states armed forces base', 'unity church', 'university', 'university department',
  'university hospital', 'university library', 'upholstery cleaning service', 'upholstery shop',
  'urban planning department', 'urgent care center', 'urologist', 'urology clinic',
  'uruguayan restaurant', 'used appliance store', 'used auto parts store', 'used bicycle shop',
  'used book store', 'used car dealer', 'used cd store', 'used clothing store',
  'used computer store', 'used furniture store', 'used game store', 'used motorcycle dealer',
  'used musical instrument store', 'used office furniture store', 'used store fixture supplier',
  'used tire shop', 'used truck dealer', 'utility contractor', 'utility trailer dealer',
  'uyghur cuisine restaurant', 'vacation home rental agency', 'vacuum cleaner repair shop',
  'vacuum cleaner store', 'vacuum cleaning system supplier', 'valencian restaurant',
  'valet parking service', 'van rental agency', 'vaporizer store', 'variety store',
  'vascular surgeon', 'vastu consultant', 'vcr repair service', 'vegan restaurant',
  'vegetable wholesale market', 'vegetable wholesaler', 'vegetarian cafe and deli',
  'vegetarian restaurant', 'vehicle exporter', 'vehicle inspection service', 'vehicle repair',
  'vehicle repair shop', 'vehicle shipping agent', 'vehicle wrapping service', 'velodrome',
  'vending machine supplier', 'venereologist', 'venetian restaurant', 'venezuelan restaurant',
  'ventilating equipment manufacturer', 'venture capital company',
  'veterans affairs department', 'veterans center', 'veterans hospital',
  'veterans organization', 'veterinarian', 'veterinary care', 'veterinary pharmacy',
  'video arcade', 'video camera repair service', 'video conferencing equipment supplier',
  'video conferencing service', 'video duplication service', 'video editing service',
  'video equipment repair service', 'video game rental kiosk', 'video game rental store',
  'video game store', 'video karaoke', 'video production service', 'video store',
  'vietnamese restaurant', 'villa', 'village hall', 'vineyard', 'vineyard church',
  'vintage clothing store', 'vinyl sign shop', 'violin shop', 'virtual office rental',
  'visa and passport office', 'visa consulting service', 'visitor center',
  'vitamin & supplements store', 'vocal instructor', 'vocational gymnasium school',
  'vocational school', 'vocational secondary school', 'volkswagen dealer', 'volleyball club',
  'volleyball court', 'volleyball instructor', 'volunteer organization', 'volvo dealer',
  'voter registration office', 'waldorf kindergarten', 'waldorf school', 'walk-in clinic',
  'wallpaper installer', 'wallpaper store', 'war museum', 'warehouse', 'warehouse club',
  'warehouse store', 'washer & dryer repair service', 'washer & dryer store',
  'waste management service', 'waste transfer station', 'watch manufacturer',
  'watch repair service', 'watch store', 'water cooler supplier',
  'water damage restoration service', 'water filter supplier', 'water jet cutting service',
  'water mill', 'water park', 'water polo pool', 'water pump supplier',
  'water purification company', 'water ski shop', 'water skiing club',
  'water skiing instructor', 'water skiing service', 'water softening equipment supplier',
  'water sports equipment rental service', 'water tank cleaning service',
  'water testing service', 'water treatment plant', 'water treatment supplier',
  'water utility company', 'water works', 'water works equipment supplier',
  'waterbed repair service', 'waterbed store', 'waterproofing service', 'wax museum',
  'wax supplier', 'waxing hair removal service', 'weather forecast service', 'weaving mill',
  'web designer', 'web hosting company', 'website designer', 'wedding bakery', 'wedding buffet',
  'wedding chapel', 'wedding dress rental service', 'wedding photographer', 'wedding planner',
  'wedding service', 'wedding souvenir shop', 'wedding store', 'wedding venue', 'weigh station',
  'weight loss service', 'weightlifting area', 'weir', 'welder', 'welding gas supplier',
  'welding supply store', 'well drilling contractor', 'wellness center', 'wellness hotel',
  'wellness program', 'welsh restaurant', 'wesleyan church', 'west african restaurant',
  'western apparel store', 'western restaurant', 'whale watching tour agency',
  'wheel alignment service', 'wheel store', 'wheelchair rental service',
  'wheelchair repair service', 'wheelchair store', 'wholesale bakery', 'wholesale drugstore',
  'wholesale florist', 'wholesale food store', 'wholesale grocer', 'wholesale jeweler',
  'wholesale market', 'wholesale plant nursery', 'wholesaler',
  'wholesaler household appliances', 'wi-fi spot', 'wicker store', 'wig shop',
  'wildlife and safari park', 'wildlife park', 'wildlife refuge', 'wildlife rescue service',
  'willow basket manufacturer', 'wind farm', 'wind turbine builder', 'window cleaning service',
  'window installation service', 'window supplier', 'window tinting service',
  'window treatment store', 'windsurfing store', 'wine bar', 'wine cellar', 'wine club',
  'wine storage facility', 'wine store', 'wine wholesaler and importer',
  'winemaking supply store', 'winery', 'wing chun school', 'wok restaurant',
  'women\'s clothing store', 'women\'s health clinic', 'women\'s personal trainer',
  'wood and laminate flooring supplier', 'wood floor installation service',
  'wood floor refinishing service', 'wood frame supplier', 'wood stove shop', 'wood supplier',
  'wood working class', 'woods', 'woodworker', 'woodworking supply store', 'wool store',
  'work clothes store', 'wrestling school', 'x-ray lab', 'yacht broker', 'yacht club',
  'yakatabune', 'yakiniku restaurant', 'yakisoba restaurant', 'yakitori restaurant',
  'yamaha motorcycle dealer', 'yarn store', 'yemeni restaurant', 'yeshiva', 'yoga instructor',
  'yoga retreat center', 'yoga studio', 'youth care service', 'youth center',
  'youth clothing store', 'youth club', 'youth hostel', 'youth organization',
  'youth social services organization', 'yucatan restaurant', 'zoo',
]);

export default GOOGLE_PLACE_CATEGORIES;
