import { DataTypes, Model } from 'sequelize';
import { sequelize } from '../database/connection.js';

class ProvisioningSession extends Model { }

ProvisioningSession.init({
    id: {
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4,
        primaryKey: true
    },
    sessionCode: {
        type: DataTypes.UUID,
        allowNull: false,
        unique: true,
        comment: 'The UUIDv4 generated by the tablet used for the QR code channel'
    },
    status: {
        type: DataTypes.ENUM('pending', 'fulfilled', 'expired'),
        defaultValue: 'pending'
    },
    deviceKey: {
        type: DataTypes.STRING,
        allowNull: true,
        comment: 'The key provided by the admin to be sent to the tablet'
    },
    ipAddress: {
        type: DataTypes.STRING,
        allowNull: true
    },
    expiresAt: {
        type: DataTypes.DATE,
        allowNull: false
    }
}, {
    sequelize,
    modelName: 'ProvisioningSession',
    tableName: 'provisioning_sessions',
    indexes: [
        { fields: ['sessionCode'], unique: true },
        { fields: ['status'] }
    ]
});

export default ProvisioningSession;
