services:
  db:
    image: postgres:15-alpine
    container_name: mktr-postgres
    environment:
      POSTGRES_USER: mktr
      POSTGRES_PASSWORD: mktr
      POSTGRES_DB: mktr
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mktr"]
      interval: 3s
      timeout: 3s
      retries: 20
    ports: ["5433:5432"]
    volumes: [postgres_data:/var/lib/postgresql/data]

  redis:
    image: redis:7-alpine
    container_name: mktr-redis
    command: ["redis-server", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 20
    ports: ["6379:6379"]

  auth:
    container_name: mktr-auth
    build: { context: ../services/auth-service }
    environment:
      PORT: 4001
      AUTH_ISSUER: http://auth:4001
      AUTH_AUDIENCE: mktr
    ports: ["4001:4001"]
    depends_on:
      db: { condition: service_healthy }

  monolith:
    container_name: mktr-monolith
    build: { context: ../backend }
    environment:
      PORT: 3001
      ENABLE_DOMAIN_PREFIXES: "true"
      ENABLE_AUTH_MAPPING: "true"
      ENABLE_LEGACY_LEADGEN: "true"
      AUTH_JWKS_URL: http://auth:4001/.well-known/jwks.json
      AUTH_ISSUER: http://auth:4001
      AUTH_AUDIENCE: mktr
      DATABASE_URL: postgres://mktr:mktr@db:5432/mktr
      REDIS_URL: redis://redis:6379/0
    ports: ["3001:3001"]
    depends_on:
      db: { condition: service_healthy }
      auth: { condition: service_started }

  leadgen:
    container_name: mktr-leadgen
    build: { context: ../services/leadgen-service }
    environment:
      PORT: 4002
      LOG_LEVEL: info
      DATABASE_URL: postgres://mktr:mktr@db:5432/mktr
      PG_SCHEMA: leadgen
      AUTH_JWKS_URL: http://auth:4001/.well-known/jwks.json
      AUTH_ISSUER: http://auth:4001
      AUTH_AUDIENCE: mktr
    ports: ["4002:4002"]
    depends_on:
      db: { condition: service_healthy }
      auth: { condition: service_started }

  gateway:
    container_name: mktr-gateway
    build: { context: ../services/gateway }
    environment:
      PORT: 4000
      AUTH_JWKS_URL: http://auth:4001/.well-known/jwks.json
      AUTH_ISSUER: http://auth:4001
      AUTH_AUDIENCE: mktr
      MONOLITH_URL: http://monolith:3001
      AUTH_URL: http://auth:4001
      LEADGEN_URL: http://leadgen:4002
    ports: ["4000:4000"]
    depends_on:
      auth: { condition: service_started }
      monolith: { condition: service_started }
      leadgen: { condition: service_started }

volumes:
  postgres_data:
