/**
 * Shared test fixtures for the "Protection Personality" quiz (quizId protection-personality, v2).
 * Imported by BOTH the backend jest suite and the frontend vitest suite so the
 * server scorer (backend/src/services/quizScoringService.js) and client scorer
 * (src/lib/quizScoring.js) are validated against the SAME golden cases.
 *
 * `goldenCases` expectations were produced by an independent Python oracle
 * (see the quiz content doc), using round-half-up for readiness to match JS
 * Math.round. They are NOT generated by the JS scorer under test.
 *
 * `.mjs` so both jest (experimental-vm-modules) and vitest treat it as ESM.
 */

// Scoring-relevant slice of campaign.design_config.quiz (images/copy omitted).
export const quizDef = {
  enabled: true,
  quizId: 'protection-personality',
  version: 2,
  scoring: {
    method: 'profile-sum',
    tiebreak: 'prepared-first',
    profileOrder: ['the-rock', 'the-strategist', 'the-dreamer', 'the-free-spirit'],
    readiness: {
      enabled: true,
      label: 'Your Protection Readiness',
      rankFactor: { 'the-rock': 1.0, 'the-strategist': 0.66, 'the-dreamer': 0.33, 'the-free-spirit': 0.0 },
    },
    leadScore: {
      enabled: true,
      tagPoints: {
        exposed: 3, uncertain: 2, covered: 1, confident: 0,
        'family-dependents': 3, couple: 2, single: 1, 'single-free': 1,
        'life-income': 2, 'savings-retirement': 2, 'nurture-warm': 1, 'nurture-cold': 0,
      },
      bands: [
        { gte: 6, label: 'Hot', badge: '🔥' },
        { gte: 3, label: 'Warm', badge: '🌤️' },
        { label: 'Cool', badge: '❄️' },
      ],
    },
  },
  steps: [
    { id: 'step1', questions: [{ id: 'q1_weekend', prompt: 'Pick your ideal weekend', weight: 1, options: [
      { id: 'cosy',      scores: { 'the-rock': 1 } },
      { id: 'mix',       scores: { 'the-strategist': 1 } },
      { id: 'adventure', scores: { 'the-dreamer': 1 } },
      { id: 'night',     scores: { 'the-free-spirit': 1 } },
    ] }] },
    { id: 'step2', questions: [{ id: 'q2_payday', prompt: 'Payday hits. First move?', weight: 2, options: [
      { id: 'save',  scores: { 'the-rock': 1 } },
      { id: 'split', scores: { 'the-strategist': 1 } },
      { id: 'bills', scores: { 'the-dreamer': 1 } },
      { id: 'treat', scores: { 'the-free-spirit': 1 } },
    ] }] },
    { id: 'step3', questions: [{ id: 'q3_circle', prompt: "Who's in your circle right now?", weight: 2, options: [
      { id: 'family',  scores: { 'the-rock': 1 },        tag: 'family-dependents' },
      { id: 'partner', scores: { 'the-strategist': 1 }, tag: 'couple' },
      { id: 'solo',    scores: { 'the-dreamer': 1 },    tag: 'single' },
      { id: 'free',    scores: { 'the-free-spirit': 1 },tag: 'single-free' },
    ] }] },
    { id: 'step4', questions: [{ id: 'q4_worry', prompt: "The 'what if' that nags you most?", weight: 1, options: [
      { id: 'family_ok',  scores: { 'the-rock': 1 },        tag: 'life-income' },
      { id: 'saving',     scores: { 'the-strategist': 1 }, tag: 'savings-retirement' },
      { id: 'eventually', scores: { 'the-dreamer': 1 },    tag: 'nurture-warm' },
      { id: 'avoid',      scores: { 'the-free-spirit': 1 },tag: 'nurture-cold' },
    ] }] },
    { id: 'step5', questions: [{ id: 'q5_protected', prompt: 'How protected do you feel right now?', weight: 3, options: [
      { id: 'solid',   scores: { 'the-rock': 1 },        tag: 'confident' },
      { id: 'basics',  scores: { 'the-strategist': 1 }, tag: 'covered' },
      { id: 'patchy',  scores: { 'the-dreamer': 1 },    tag: 'uncertain' },
      { id: 'exposed', scores: { 'the-free-spirit': 1 },tag: 'exposed' },
    ] }] },
    { id: 'step6', questions: [{ id: 'q6_bill', prompt: 'A surprise $5,000 bill lands tomorrow. You…', weight: 3, options: [
      { id: 'fund',   scores: { 'the-rock': 1 } },
      { id: 'sting',  scores: { 'the-strategist': 1 } },
      { id: 'credit', scores: { 'the-dreamer': 1 } },
      { id: 'later',  scores: { 'the-free-spirit': 1 } },
    ] }] },
  ],
  resultProfiles: [
    { id: 'the-rock',        title: 'The Rock',        agentAngle: 'optimise / legacy / wealth transfer' },
    { id: 'the-strategist',  title: 'The Strategist',  agentAngle: 'savings / retirement top-up' },
    { id: 'the-dreamer',     title: 'The Big Dreamer', agentAngle: 'starter health + CI, then savings' },
    { id: 'the-free-spirit', title: 'The Free Spirit', agentAngle: 'affordable starter protection' },
  ],
};

const A = (q, v) => ({ qid: q, value: v });

// Golden cases — expectations from the independent Python oracle (round-half-up).
export const goldenCases = [
  {
    name: 'all_rock',
    answers: [A('q1_weekend', 'cosy'), A('q2_payday', 'save'), A('q3_circle', 'family'), A('q4_worry', 'family_ok'), A('q5_protected', 'solid'), A('q6_bill', 'fund')],
    expect: { profileId: 'the-rock', readiness: 100, leadPoints: 5, band: 'Warm' },
  },
  {
    name: 'all_free_spirit',
    answers: [A('q1_weekend', 'night'), A('q2_payday', 'treat'), A('q3_circle', 'free'), A('q4_worry', 'avoid'), A('q5_protected', 'exposed'), A('q6_bill', 'later')],
    expect: { profileId: 'the-free-spirit', readiness: 0, leadPoints: 4, band: 'Warm' },
  },
  {
    name: 'all_strategist',
    answers: [A('q1_weekend', 'mix'), A('q2_payday', 'split'), A('q3_circle', 'partner'), A('q4_worry', 'saving'), A('q5_protected', 'basics'), A('q6_bill', 'sting')],
    expect: { profileId: 'the-strategist', readiness: 66, leadPoints: 5, band: 'Warm' },
  },
  {
    name: 'all_dreamer',
    answers: [A('q1_weekend', 'adventure'), A('q2_payday', 'bills'), A('q3_circle', 'solo'), A('q4_worry', 'eventually'), A('q5_protected', 'patchy'), A('q6_bill', 'credit')],
    expect: { profileId: 'the-dreamer', readiness: 33, leadPoints: 4, band: 'Warm' },
  },
  {
    name: 'hot_rock_exposed', // 66.5 -> 67 under round-half-up (Math.round)
    answers: [A('q1_weekend', 'cosy'), A('q2_payday', 'save'), A('q3_circle', 'family'), A('q4_worry', 'family_ok'), A('q5_protected', 'exposed'), A('q6_bill', 'sting')],
    expect: { profileId: 'the-rock', readiness: 67, leadPoints: 8, band: 'Hot' },
  },
  {
    name: 'mixed_dreamer',
    answers: [A('q1_weekend', 'adventure'), A('q2_payday', 'split'), A('q3_circle', 'solo'), A('q4_worry', 'saving'), A('q5_protected', 'patchy'), A('q6_bill', 'later')],
    expect: { profileId: 'the-dreamer', readiness: 33, leadPoints: 5, band: 'Warm' },
  },
  {
    name: 'prepared_yolo_weekend',
    answers: [A('q1_weekend', 'cosy'), A('q2_payday', 'save'), A('q3_circle', 'free'), A('q4_worry', 'family_ok'), A('q5_protected', 'solid'), A('q6_bill', 'fund')],
    expect: { profileId: 'the-rock', readiness: 83, leadPoints: 3, band: 'Warm' },
  },
  {
    name: 'cool_freespirit',
    answers: [A('q1_weekend', 'night'), A('q2_payday', 'treat'), A('q3_circle', 'free'), A('q4_worry', 'avoid'), A('q5_protected', 'solid'), A('q6_bill', 'later')],
    expect: { profileId: 'the-free-spirit', readiness: 25, leadPoints: 1, band: 'Cool' },
  },
];

// A constructed 2-way tie (rock=6, free-spirit=6) to exercise the tiebreak knob.
export const tiebreakCase = {
  answers: [A('q1_weekend', 'cosy'), A('q2_payday', 'treat'), A('q3_circle', 'family'), A('q4_worry', 'avoid'), A('q5_protected', 'solid'), A('q6_bill', 'later')],
  preparedFirst: 'the-rock',
  gapFirst: 'the-free-spirit',
  readiness: 50,
  leadPoints: 3,
  band: 'Warm',
};
