name: smoke-phase-b

on:
  pull_request:
    paths:
      - 'services/leadgen-service/**'
      - 'services/gateway/**'
      - 'infra/docker-compose.yml'

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Start compose
        run: |
          docker compose -f infra/docker-compose.yml up -d --build db auth monolith gateway leadgen
          echo 'Waiting for services...'
          for i in {1..60}; do curl -sf http://localhost:4001/.well-known/jwks.json && break; sleep 2; done
      - name: Login to auth-service
        id: login
        run: |
          TOKEN=$(curl -s -X POST http://localhost:4001/v1/auth/login -H 'Content-Type: application/json' -d '{"email":"admin@example.com","password":"admin123"}' | jq -r '.data.token')
          if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then echo 'No token'; exit 1; fi
          echo "token=$TOKEN" >> $GITHUB_OUTPUT
      - name: Leadgen health
        run: |
          curl -s -H "Authorization: Bearer ${{ steps.login.outputs.token }}" http://localhost:4000/api/leadgen/health | tee /tmp/health.json
          jq -e '.ok == true and .service == "leadgen"' /tmp/health.json
      - name: Create QR and list
        run: |
          curl -s -X POST http://localhost:4000/api/leadgen/v1/qrcodes -H "Authorization: Bearer ${{ steps.login.outputs.token }}" -H 'Content-Type: application/json' -d '{"code":"CI-QR-1","status":"active"}' | tee /tmp/create.json
          curl -s -H "Authorization: Bearer ${{ steps.login.outputs.token }}" http://localhost:4000/api/leadgen/v1/qrcodes | jq -e '.success == true'
      - name: Teardown
        if: always()
        run: docker compose -f infra/docker-compose.yml down -v


